### ISSUE TITLE
make and windows are not compatible. 

### ISSUE THREAD

**Issue by AdmcCarthy** [Statoil/data-science-template#22]
Within the readme.md within {{cookiecutter.package_name}}
```
cd docs/writeup
make html
```

There are a proportion using this on a windows operating system and the make command does not work here.

Either needs a suggestion for windows or a clarification that this does not work on a windows operating system.

Please don't remove the Sphinx template as it's a very good idea to include from start of project.

**Comment by mahewitt** [comment]
There is actually a batch file make.bat that will be run on windows. Updated the README to clarify this
